server:
  port: 8080
  session:
    timeout:1*60*1000

spring:
  #数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8
    username: blog
    password: Blog.12
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 30
      minimum-idle: 5
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    continue-on-error: true
    jpa:
      hibernate:
        ddl-auto: none

  #模板引擎
  freemarker:
    cache: false
    request-context-attribute: request
    template-loader-path: classpath:/templates
    suffix: .html
#    view-names: index

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.lowen.blog.model
  config-location: classpath:mybatis.xml

#配置日志
logging:
  #配置日志文件路径
  level:
    com.lowen.blog: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: info.log


#logging:
#  config: classpath:log4j2.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
